replacements = {
    # buildFox
    "private static CarcassDefinition buildFox() {\n        return new CarcassDefinition(\n                \"fox\",\n                BuiltInRegistries.ENTITY_TYPE.getOrThrow(\n                                ResourceKey.create(Registries.ENTITY_TYPE, Identifier.parse(\"minecraft:fox\")))\n                        .value(),\n                true,\n                true,\n                true,\n                // Fox drops raw_fox_meat\n                java.util.List.of(net.minecraft.world.item.Items.SWEET_BERRIES)); // Fox doesn't have a vanilla meat drop, using sweet berries as placeholder": 
    "private static CarcassDefinition buildFox() {\n        return new CarcassDefinition(\n                \"fox\",\n                BuiltInRegistries.ENTITY_TYPE.getOrThrow(\n                                ResourceKey.create(Registries.ENTITY_TYPE, Identifier.parse(\"minecraft:fox\")))\n                        .value(),\n                true,\n                true,\n                true,\n                true,\n                3,\n                // Fox drops raw_fox_meat\n                java.util.List.of(net.minecraft.world.item.Items.SWEET_BERRIES)); // Fox doesn't have a vanilla meat drop, using sweet berries as placeholder",

    # buildWolf
    "private static CarcassDefinition buildWolf() {\n        return new CarcassDefinition(\n                \"wolf\",\n                BuiltInRegistries.ENTITY_TYPE.getOrThrow(\n                                ResourceKey.create(Registries.ENTITY_TYPE, Identifier.parse(\"minecraft:wolf\")))\n                        .value(),\n                true,\n                true,\n                true,\n                // Wolf drops wolf_pelt\n                java.util.List.of(net.minecraft.world.item.Items.BONE));": 
    "private static CarcassDefinition buildWolf() {\n        return new CarcassDefinition(\n                \"wolf\",\n                BuiltInRegistries.ENTITY_TYPE.getOrThrow(\n                                ResourceKey.create(Registries.ENTITY_TYPE, Identifier.parse(\"minecraft:wolf\")))\n                        .value(),\n                true,\n                true,\n                true,\n                true,\n                3,\n                // Wolf drops wolf_pelt\n                java.util.List.of(net.minecraft.world.item.Items.BONE));",

    # buildCAMEL
    "private static CarcassDefinition buildCAMEL() {\n        return new CarcassDefinition(\n                \"camel\",\n                BuiltInRegistries.ENTITY_TYPE.getOrThrow(\n                                ResourceKey.create(Registries.ENTITY_TYPE, Identifier.parse(\"minecraft:camel\")))\n                        .value(),\n                true,\n                true,\n                true,\n                // camel drops raw_camel_meat\n                java.util.List.of(ModItems.RAW_CAMEL_MEAT));": 
    "private static CarcassDefinition buildCAMEL() {\n        return new CarcassDefinition(\n                \"camel\",\n                BuiltInRegistries.ENTITY_TYPE.getOrThrow(\n                                ResourceKey.create(Registries.ENTITY_TYPE, Identifier.parse(\"minecraft:camel\")))\n                        .value(),\n                true,\n                true,\n                true,\n                true,\n                3,\n                // camel drops raw_camel_meat\n                java.util.List.of(ModItems.RAW_CAMEL_MEAT));",

    # buildDONKEY
    "private static CarcassDefinition buildDONKEY() {\n        return new CarcassDefinition(\n                \"donkey\",\n                BuiltInRegistries.ENTITY_TYPE.getOrThrow(\n                                ResourceKey.create(Registries.ENTITY_TYPE, Identifier.parse(\"minecraft:donkey\")))\n                        .value(),\n                true,\n                true,\n                true,\n                // donkey drops raw_donkey_steak\n                java.util.List.of(ModItems.RAW_DONKEY_STEAK));": 
    "private static CarcassDefinition buildDONKEY() {\n        return new CarcassDefinition(\n                \"donkey\",\n                BuiltInRegistries.ENTITY_TYPE.getOrThrow(\n                                ResourceKey.create(Registries.ENTITY_TYPE, Identifier.parse(\"minecraft:donkey\")))\n                        .value(),\n                true,\n                true,\n                true,\n                true,\n                3,\n                // donkey drops raw_donkey_steak\n                java.util.List.of(ModItems.RAW_DONKEY_STEAK));",

    # buildMULE
    "private static CarcassDefinition buildMULE() {\n        return new CarcassDefinition(\n                \"mule\",\n                BuiltInRegistries.ENTITY_TYPE.getOrThrow(\n                                ResourceKey.create(Registries.ENTITY_TYPE, Identifier.parse(\"minecraft:mule\")))\n                        .value(),\n                true,\n                true,\n                true,\n                // mule drops raw_mule_steak\n                java.util.List.of(ModItems.RAW_MULE_STEAK));": 
    "private static CarcassDefinition buildMULE() {\n        return new CarcassDefinition(\n                \"mule\",\n                BuiltInRegistries.ENTITY_TYPE.getOrThrow(\n                                ResourceKey.create(Registries.ENTITY_TYPE, Identifier.parse(\"minecraft:mule\")))\n                        .value(),\n                true,\n                true,\n                true,\n                true,\n                3,\n                // mule drops raw_mule_steak\n                java.util.List.of(ModItems.RAW_MULE_STEAK));",

    # buildOCELOT
    "private static CarcassDefinition buildOCELOT() {\n        return new CarcassDefinition(\n                \"ocelot\",\n                BuiltInRegistries.ENTITY_TYPE.getOrThrow(\n                                ResourceKey.create(Registries.ENTITY_TYPE, Identifier.parse(\"minecraft:ocelot\")))\n                        .value(),\n                true,\n                true,\n                true,\n                // ocelot drops raw_ocelot_meat\n                java.util.List.of(ModItems.RAW_OCELOT_MEAT));": 
    "private static CarcassDefinition buildOCELOT() {\n        return new CarcassDefinition(\n                \"ocelot\",\n                BuiltInRegistries.ENTITY_TYPE.getOrThrow(\n                                ResourceKey.create(Registries.ENTITY_TYPE, Identifier.parse(\"minecraft:ocelot\")))\n                        .value(),\n                true,\n                true,\n                true,\n                true,\n                3,\n                // ocelot drops raw_ocelot_meat\n                java.util.List.of(ModItems.RAW_OCELOT_MEAT));",

    # buildPANDA
    "private static CarcassDefinition buildPANDA() {\n        return new CarcassDefinition(\n                \"panda\",\n                BuiltInRegistries.ENTITY_TYPE.getOrThrow(\n                                ResourceKey.create(Registries.ENTITY_TYPE, Identifier.parse(\"minecraft:panda\")))\n                        .value(),\n                true,\n                true,\n                true,\n                // panda drops raw_panda_steak\n                java.util.List.of(ModItems.RAW_PANDA_STEAK));": 
    "private static CarcassDefinition buildPANDA() {\n        return new CarcassDefinition(\n                \"panda\",\n                BuiltInRegistries.ENTITY_TYPE.getOrThrow(\n                                ResourceKey.create(Registries.ENTITY_TYPE, Identifier.parse(\"minecraft:panda\")))\n                        .value(),\n                true,\n                true,\n                true,\n                true,\n                3,\n                // panda drops raw_panda_steak\n                java.util.List.of(ModItems.RAW_PANDA_STEAK));",

    # buildPOLAR_BEAR
    "private static CarcassDefinition buildPOLAR_BEAR() {\n        return new CarcassDefinition(\n                \"polar_bear\",\n                BuiltInRegistries.ENTITY_TYPE.getOrThrow(\n                                ResourceKey.create(Registries.ENTITY_TYPE, Identifier.parse(\"minecraft:polar_bear\")))\n                        .value(),\n                true,\n                true,\n                true,\n                // polar_bear drops raw_polar_bear_meat\n                java.util.List.of(ModItems.RAW_POLAR_BEAR_MEAT));": 
    "private static CarcassDefinition buildPOLAR_BEAR() {\n        return new CarcassDefinition(\n                \"polar_bear\",\n                BuiltInRegistries.ENTITY_TYPE.getOrThrow(\n                                ResourceKey.create(Registries.ENTITY_TYPE, Identifier.parse(\"minecraft:polar_bear\")))\n                        .value(),\n                true,\n                true,\n                true,\n                true,\n                3,\n                // polar_bear drops raw_polar_bear_meat\n                java.util.List.of(ModItems.RAW_POLAR_BEAR_MEAT));",

    # buildHOGLIN
    "private static CarcassDefinition buildHOGLIN() {\n        return new CarcassDefinition(\n                \"hoglin\",\n                BuiltInRegistries.ENTITY_TYPE.getOrThrow(\n                                ResourceKey.create(Registries.ENTITY_TYPE, Identifier.parse(\"minecraft:hoglin\")))\n                        .value(),\n                true,\n                true,\n                true,\n                // hoglin drops raw_hoglin_chunk\n                java.util.List.of(ModItems.RAW_HOGLIN_CHUNK));": 
    "private static CarcassDefinition buildHOGLIN() {\n        return new CarcassDefinition(\n                \"hoglin\",\n                BuiltInRegistries.ENTITY_TYPE.getOrThrow(\n                                ResourceKey.create(Registries.ENTITY_TYPE, Identifier.parse(\"minecraft:hoglin\")))\n                        .value(),\n                true,\n                true,\n                true,\n                true,\n                3,\n                // hoglin drops raw_hoglin_chunk\n                java.util.List.of(ModItems.RAW_HOGLIN_CHUNK));",

    # buildZOGLIN
    "private static CarcassDefinition buildZOGLIN() {\n        return new CarcassDefinition(\n                \"zoglin\",\n                BuiltInRegistries.ENTITY_TYPE.getOrThrow(\n                                ResourceKey.create(Registries.ENTITY_TYPE, Identifier.parse(\"minecraft:zoglin\")))\n                        .value(),\n                true,\n                true,\n                false,\n                // zoglin drops minecraft:rotten_flesh\n                java.util.List.of(net.minecraft.world.item.Items.ROTTEN_FLESH));": 
    "private static CarcassDefinition buildZOGLIN() {\n        return new CarcassDefinition(\n                \"zoglin\",\n                BuiltInRegistries.ENTITY_TYPE.getOrThrow(\n                                ResourceKey.create(Registries.ENTITY_TYPE, Identifier.parse(\"minecraft:zoglin\")))\n                        .value(),\n                true,\n                true,\n                false,\n                true,\n                3,\n                // zoglin drops minecraft:rotten_flesh\n                java.util.List.of(net.minecraft.world.item.Items.ROTTEN_FLESH));",

    # buildDOLPHIN
    "private static CarcassDefinition buildDOLPHIN() {\n        return new CarcassDefinition(\n                \"dolphin\",\n                BuiltInRegistries.ENTITY_TYPE.getOrThrow(\n                                ResourceKey.create(Registries.ENTITY_TYPE, Identifier.parse(\"minecraft:dolphin\")))\n                        .value(),\n                true,\n                true,\n                true,\n                // dolphin drops raw_dolphin_meat\n                java.util.List.of(ModItems.RAW_DOLPHIN_MEAT));": 
    "private static CarcassDefinition buildDOLPHIN() {\n        return new CarcassDefinition(\n                \"dolphin\",\n                BuiltInRegistries.ENTITY_TYPE.getOrThrow(\n                                ResourceKey.create(Registries.ENTITY_TYPE, Identifier.parse(\"minecraft:dolphin\")))\n                        .value(),\n                true,\n                true,\n                true,\n                true,\n                3,\n                // dolphin drops raw_dolphin_meat\n                java.util.List.of(ModItems.RAW_DOLPHIN_MEAT));",

    # buildBAT
    "private static CarcassDefinition buildBAT() {\n        return new CarcassDefinition(\n                \"bat\",\n                BuiltInRegistries.ENTITY_TYPE.getOrThrow(\n                                ResourceKey.create(Registries.ENTITY_TYPE, Identifier.parse(\"minecraft:bat\")))\n                        .value(),\n                true,\n                true,\n                true,\n                // bat drops raw_bat_meat\n                java.util.List.of(net.minecraft.world.item.Items.BONE));": 
    "private static CarcassDefinition buildBAT() {\n        return new CarcassDefinition(\n                \"bat\",\n                BuiltInRegistries.ENTITY_TYPE.getOrThrow(\n                                ResourceKey.create(Registries.ENTITY_TYPE, Identifier.parse(\"minecraft:bat\")))\n                        .value(),\n                true,\n                true,\n                true,\n                true,\n                3,\n                // bat drops raw_bat_meat\n                java.util.List.of(net.minecraft.world.item.Items.BONE));",

    # buildSILVERFISH - no skin
    "private static CarcassDefinition buildSILVERFISH() {\n        return new CarcassDefinition(\n                \"silverfish\",\n                BuiltInRegistries.ENTITY_TYPE.getOrThrow(\n                                ResourceKey.create(Registries.ENTITY_TYPE, Identifier.parse(\"minecraft:silverfish\")))\n                        .value(),\n                true,\n                true,\n                false,\n                Carcasses::silverfishHanging,\n                Carcasses::silverfishLying,\n                Carcasses::silverfishHead,\n                Carcasses::silverfishHeadMount,\n                Carcasses::silverfishLying,  // no skeleton\n                // silverfish drops raw_silverfish_chunks\n                java.util.List.of(net.minecraft.world.item.Items.BONE));": 
    "private static CarcassDefinition buildSILVERFISH() {\n        return new CarcassDefinition(\n                \"silverfish\",\n                BuiltInRegistries.ENTITY_TYPE.getOrThrow(\n                                ResourceKey.create(Registries.ENTITY_TYPE, Identifier.parse(\"minecraft:silverfish\")))\n                        .value(),\n                true,\n                true,\n                false,\n                false,\n                3,\n                Carcasses::silverfishHanging,\n                Carcasses::silverfishLying,\n                Carcasses::silverfishHead,\n                Carcasses::silverfishHeadMount,\n                Carcasses::silverfishLying,  // no skeleton\n                // silverfish drops raw_silverfish_chunks\n                java.util.List.of(net.minecraft.world.item.Items.BONE));",

    # buildENDERMITE - no skin
    "private static CarcassDefinition buildENDERMITE() {\n        return new CarcassDefinition(\n                \"endermite\",\n                BuiltInRegistries.ENTITY_TYPE.getOrThrow(\n                                ResourceKey.create(Registries.ENTITY_TYPE, Identifier.parse(\"minecraft:endermite\")))\n                        .value(),\n                true,\n                true,\n                false,\n                Carcasses::endermiteHanging,\n                Carcasses::endermiteLying,\n                Carcasses::endermiteHead,\n                Carcasses::endermiteHeadMount,\n                Carcasses::endermiteLying,  // no skeleton\n                // endermite drops raw_endermite_chunks\n                java.util.List.of(net.minecraft.world.item.Items.BONE));": 
    "private static CarcassDefinition buildENDERMITE() {\n        return new CarcassDefinition(\n                \"endermite\",\n                BuiltInRegistries.ENTITY_TYPE.getOrThrow(\n                                ResourceKey.create(Registries.ENTITY_TYPE, Identifier.parse(\"minecraft:endermite\")))\n                        .value(),\n                true,\n                true,\n                false,\n                false,\n                3,\n                Carcasses::endermiteHanging,\n                Carcasses::endermiteLying,\n                Carcasses::endermiteHead,\n                Carcasses::endermiteHeadMount,\n                Carcasses::endermiteLying,  // no skeleton\n                // endermite drops raw_endermite_chunks\n                java.util.List.of(net.minecraft.world.item.Items.BONE));",

    # buildBEE - 2 cuts, no skin
    "private static CarcassDefinition buildBEE() {\n        return new CarcassDefinition(\n                \"bee\",\n                BuiltInRegistries.ENTITY_TYPE.getOrThrow(\n                                ResourceKey.create(Registries.ENTITY_TYPE, Identifier.parse(\"minecraft:bee\")))\n                        .value(),\n                true,\n                false,\n                false,\n                Carcasses::beeHanging,\n                Carcasses::beeLying,\n                Carcasses::beeHead,\n                Carcasses::beeLying,  // no head mount\n                Carcasses::beeLying,  // no skeleton\n                // bee drops honey_stomach\n                java.util.List.of(net.minecraft.world.item.Items.HONEY_BOTTLE));": 
    "private static CarcassDefinition buildBEE() {\n        return new CarcassDefinition(\n                \"bee\",\n                BuiltInRegistries.ENTITY_TYPE.getOrThrow(\n                                ResourceKey.create(Registries.ENTITY_TYPE, Identifier.parse(\"minecraft:bee\")))\n                        .value(),\n                true,\n                false,\n                false,\n                false,\n                2,\n                Carcasses::beeHanging,\n                Carcasses::beeLying,\n                Carcasses::beeHead,\n                Carcasses::beeLying,  // no head mount\n                Carcasses::beeLying,  // no skeleton\n                // bee drops honey_stomach\n                java.util.List.of(net.minecraft.world.item.Items.HONEY_BOTTLE));",
}

with open("Carcasses.java", "r") as f:
    content = f.read()

for old, new in replacements.items():
    if old in content:
        content = content.replace(old, new)
        print("Replaced one")
    else:
        print("NOT FOUND:", old[:80])

with open("Carcasses.java", "w") as f:
    f.write(content)

print("Done!")